apiVersion: config.openshift.io/v1
kind: Project
metadata:
  annotations:
    release.openshift.io/create-only: "true"
    argocd.argoproj.io/sync-options: Prune=false
  name: cluster
spec:
  projectRequestMessage: To provision Projects you must request access in https://labs.opentlc.com or https://rhpds.redhat.com. Tested with ArgoCD. Updated just now.
  projectRequestTemplate:
    name: project-request
